# name: Origin Repository Workflow

# on:
#   pull_request:
#     branches:
#       - main
#   push:

# jobs:
#   cross-repo-pipeline:
#     runs-on: ubuntu-latest
#     steps: #here starts the action's setup
#       - name: cross-repo-pipeline-trigger
#         uses: amandastecz/pipeline-trigger@v1.1.1
#         with:
#           pat-token: ${{ secrets.CROSS_REPO_PIPELINE_TRIGGER_PAT_1 }} # add a secret called PAT_TOKEN
#           owner: akm-devops #changeme
#           repo: repo-1 #changeme

name: Notify ghidra-ci

on:
  push:
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-20.04
    steps:
      - name: Create repository dispatch event
        env:
          GITHUB_TOKEN: ${{ secrets.CROSS_REPO_PIPELINE_TRIGGER_PAT_1 }}
        run: |
          gh api repos/akm-devops/repo-1/dispatches \
              --raw-field event_type=mytrigger